CREATE TABLE [staging].[AccountingEntities] (
    [Id]                  INT            IDENTITY (1, 1) NOT NULL,
    [ErpId]               VARCHAR (10)   NOT NULL,
    [cin]                 VARCHAR (20)   NULL,
    [tin]                 VARCHAR (20)   NULL,
    [sid]                 VARCHAR (20)   NULL,
    [titleAE]             NVARCHAR (500) NULL,
    [city]                NVARCHAR (200) NULL,
    [street]              NVARCHAR (200) NULL,
    [zip]                 VARCHAR (10)   NULL,
    [established]         DATE           NULL,
    [cancellation]        DATE           NULL,
    [legalFormId]         VARCHAR (100)  NULL,
    [skNaceId]            VARCHAR (100)  NULL,
    [organizationSizeId]  VARCHAR (100)  NULL,
    [ownershipTypeId]     VARCHAR (100)  NULL,
    [regionId]            VARCHAR (100)  NULL,
    [districtId]          VARCHAR (100)  NULL,
    [registerredOfficeId] VARCHAR (100)  NULL,
    [consolidated]        BIT            NULL,
    [dataSource]          VARCHAR (30)   NULL,
    [lastModification]    DATE           NULL,
    CONSTRAINT [PK_staging_AccountingEntities] PRIMARY KEY CLUSTERED ([Id] ASC)
);

