CREATE TABLE [staging].[ReportContents] (
    [Id]                          INT           NOT NULL,
    [FinancialReportId]           INT           NULL,
    [coverPageTitle]              VARCHAR (MAX) NULL,
    [coverPageIco]                VARCHAR (20)  NULL,
    [coverPageDic]                VARCHAR (20)  NULL,
    [coverPageSid]                VARCHAR (20)  NULL,
    [coverPageAddress]            VARCHAR (MAX) NULL,
    [coverPageLegalFormId]        VARCHAR (100) NULL,
    [coverPageSkNaceId]           VARCHAR (100) NULL,
    [coverPageType]               VARCHAR (50)  NULL,
    [coverPageConsolidated]       BIT           NULL,
    [coverPageConsolidatedCG]     BIT           NULL,
    [coverPageSummaryPA]          BIT           NULL,
    [coverPageTypeUnit]           VARCHAR (50)  NULL,
    [commercialRegister]          VARCHAR (MAX) NULL,
    [fundName]                    VARCHAR (500) NULL,
    [leiCode]                     VARCHAR (20)  NULL,
    [periodFrom]                  VARCHAR (7)   NULL,
    [periodTo]                    VARCHAR (7)   NULL,
    [previousPeriodFrom]          VARCHAR (7)   NULL,
    [previousPeriodTo]            VARCHAR (7)   NULL,
    [completionDate]              DATE          NULL,
    [approvalDate]                DATE          NULL,
    [preparationDate]             DATE          NULL,
    [assemblyDate]                DATE          NULL,
    [auditorReportAttachmentDate] DATE          NULL,
    CONSTRAINT [PK_staging_ReportContents] PRIMARY KEY CLUSTERED ([Id] ASC)
);

